apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir
  namespace: observability
data:
  mimir.yaml: |
    target: all
    multitenancy_enabled: false
    server:
      http_listen_port: 9009
    blocks_storage:
      backend: filesystem
      filesystem:
        dir: /data/mimir/blocks
      tsdb:
        dir: /data/mimir/tsdb
    compactor:
      data_dir: /data/mimir/compactor
      sharding_ring:
        kvstore:
          store: inmemory
    ingester:
      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: inmemory
        replication_factor: 1
    distributor:
      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: inmemory
    store_gateway:
      sharding_ring:
        replication_factor: 1
