apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lgtm-grafana-pvc
  namespace: observability
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: lgtm-grafana-sc
  resources:
    requests:
      storage: 10Gi
