apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lgtm-grafana-sc
provisioner: nfs.csi.k8s.io
parameters:
  server: [IP_ADDRESS]
  share: /mnt/nfs/lgtm
  subDir: grafana
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=3
